/**:
  ros__parameters:
    alevel: 0
    base_link: base_link
    filter_update_cycle: 100
    map_file: ./ws02/install/mr_pf/share/mr_pf/config/maps/cave.png
    map_link: map
    motion_model.alpha1: 0.3
    motion_model.alpha2: 0.1
    motion_model.alpha3: 0.3
    motion_model.alpha4: 0.1
    motion_model.alpha5: 0.3
    motion_model.alpha6: 0.1
    motion_model.disable: false
    motion_model.duration_offset: 0.0
    nr_of_samples: 100
    parameter_update_cycle: 2000
    resample.continues_reset: false
    resample.noise_orientation: 0.0
    resample.noise_position: 0.0
    resample.rate: 0.05
    resample.strategy: low variance
    sensor_model: scan
    sensor_model.lambada_short: 0.5
    sensor_model.pseudo_density_scale: 100
    sensor_model.random_beams: false
    sensor_model.rate_of_beams_used: 0.05
    sensor_model.sigma_hit: 0.5
    sensor_model.z_hit: 0.7
    sensor_model.z_max: 0.001
    sensor_model.z_rand: 0.4
    sensor_model.z_short: 0.4
    start_type_description_service: true
    use_sim_time: true
